=== donekaloinaz/PBL_6_Grupo_2/PARTE XML/Glaucoma_analysis.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Pacientes">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="paciente" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Nombre" type="xs:string"/>
                            <xs:element name="Apellido" type="xs:string"/>
                            <xs:element name="Id" type="xs:string"/>
                            <xs:element name="Mobile_phone" type="xs:string"/>
                            <xs:element name="Email" type="xs:string"/>
                            <xs:element name="Doctor" type="xs:string"/>
                            <xs:element name="Fecha_de_diagnostico" type="xs:string"/>
                            <xs:element name="Estado_de_glaucoma" type="xs:string"/>
                            <xs:element name="Imagen">
                                <xs:complexType>
                                    <xs:attribute name="Imagen" type="xs:string" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== donekaloinaz/PBL_6_Grupo_2/PARTE XML/Glaucoma_analysis.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="Glaucoma_analysis.xslt"?>

<Pacientes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Glaucoma_analysis.xsd"> 
    <paciente>
        <Nombre>Juan</Nombre>
		<Apellido>Perez</Apellido>
        <Id>1234ABDC</Id>
		<Mobile_phone>635319057</Mobile_phone>
		<Email>jperez@mondragon.edu</Email>
        <Doctor>Dr. Smith</Doctor>
		<Imagen Imagen="nervio.jpg"/>
    </paciente>
    <paciente>
        <Nombre>Ana</Nombre>
		<Apellido>Gomez</Apellido>
        <Id>67890</Id>
		<Mobile_phone>635338957</Mobile_phone>
		<Email>agomez@mondragon.edu</Email>
        <Doctor>Dr. Johnson</Doctor>
		<Imagen Imagen="nervio.jpg"/>
    </paciente>
	 <paciente>
        <Nombre>Juan</Nombre>
		<Apellido>Martin</Apellido>
        <Id>1234ABDC</Id>
		<Mobile_phone>638979057</Mobile_phone>
		<Email>jmartin@mondragon.edu</Email>
        <Doctor>Dr. Johnson</Doctor>
		<Imagen Imagen="nervio.jpg"/>
    </paciente>
	 <paciente>
        <Nombre>Pablo</Nombre>
		<Apellido>Lopez</Apellido>
        <Id>1234ABDC</Id>
		<Mobile_phone>635975057</Mobile_phone>
		<Email>plopez@mondragon.edu</Email>
        <Doctor>Dr. Johnson</Doctor>
		<Imagen Imagen="nervio.jpg"/>
    </paciente>
	 <paciente>
        <Nombre>Tomas</Nombre>
		<Apellido>Gomez</Apellido>
        <Id>1234ABDC</Id>
		<Mobile_phone>635789057</Mobile_phone>
		<Email>tgomwz@mondragon.edu</Email>
        <Doctor>Dr. Johnson</Doctor>
		<Imagen Imagen="nervio.jpg"/>
    </paciente>
</Pacientes>
